//Signup
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
//Verify OTP
export const OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_FAILURE = 'OTP_VERIFY_FAILURE';
// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
// Forgot Password
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
// Forgot Password
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';
// Reset Password
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
// Profile Picture
export const PROFILE_PIC_REQUEST = 'PROFILE_PIC_REQUEST';
export const PROFILE_PIC_SUCCESS = 'PROFILE_PIC_SUCCESS';
export const PROFILE_PIC_FAILURE = 'PROFILE_PIC_FAILURE';
// Get Address
export const GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST';
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS';
export const GET_ADDRESS_FAILURE = 'GET_ADDRESS_FAILURE';
// Post Address
export const ADDRESS_REQUEST = 'ADDRESS_REQUEST';
export const ADDRESS_SUCCESS = 'ADDRESS_SUCCESS';
export const ADDRESS_FAILURE = 'ADDRESS_FAILURE';
// User Details
export const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_FAILURE = 'USER_DATA_FAILURE';
// Remove Address
export const REMOVE_ADDRESS_REQUEST = 'REMOVE_ADDRESS_REQUEST';
export const REMOVE_ADDRESS_SUCCESS = 'REMOVE_ADDRESS_SUCCESS';
export const REMOVE_ADDRESS_FAILURE = 'REMOVE_ADDRESS_FAILURE';
// Post Days and Timing
export const DAYS_TIMING_REQUEST = 'DAYS_TIMING_REQUEST';
export const DAYS_TIMING_SUCCESS = 'DAYS_TIMING_SUCCESS';
export const DAYS_TIMING_FAILURE = 'DAYS_TIMING_FAILURE';
// Get Days and Timing
export const GET_DAYS_TIMING_REQUEST = 'GET_DAYS_TIMING_REQUEST';
export const GET_DAYS_TIMING_SUCCESS = 'GET_DAYS_TIMING_SUCCESS';
export const GET_DAYS_TIMING_FAILURE = 'GET_DAYS_TIMING_FAILURE';
// Get Business photos
export const GET_IMAGES_REQUEST = 'GET_IMAGES_REQUEST';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_FAILURE = 'GET_IMAGES_FAILURE';
// Remove Business photo
export const REMOVE_IMAGE_REQUEST = 'REMOVE_IMAGE_REQUEST';
export const REMOVE_IMAGE_SUCCESS = 'REMOVE_IMAGE_SUCCESS';
export const REMOVE_IMAGE_FAILURE = 'REMOVE_IMAGE_FAILURE';
// Post Business photos
export const BUSINESS_IMAGES_REQUEST = 'BUSINESS_IMAGES_REQUEST';
export const BUSINESS_IMAGES_SUCCESS = 'BUSINESS_IMAGES_SUCCESS';
export const BUSINESS_IMAGES_FAILURE = 'BUSINESS_IMAGES_FAILURE';
